### ISSUE TITLE
publishing the code

### ISSUE THREAD

**Issue by shidailinghun** [JundanLuo/CRefNet#1]
Hello,
Thank you for your paper and I am really interested in your work. 
When will you publish the code?

**Comment by jundanl** [comment]
Hi, thank you for your interest! I am cleaning the code (and at the same time busy with another work). The inference code can be released in 1~2 weeks, and then the training may come in one month.  If you drop me an email, I would be happy to email you when the code is released.

**Comment by JundanLuo** [comment]
Hi, thank you for your interest! I am cleaning the code (and at the same time busy with another work). I plan to release the inference code within the next 1-2 weeks, and the training within one month. If you'd like to be notified when the code is available, please feel free to send me an email (jundanluo22@gmail.com), and I'll be happy to update you as soon as it's released.

**Comment by shidailinghun** [comment]
Thanks!
